### ISSUE TITLE
Dependency on NUnit

### ISSUE THREAD

**Issue by seanamosw** [hibri/HttpMock#57]
These files have a dependency on NUnit for it's Assert.That(..) method:
RequestHandlerExpectExtensions.cs
RequestWasCalled.cs
RequestWasNotCalled.cs

For library consumers, they have to bring in NUnit even if they are using a different unit testing framework. This is a bit strange.

**Comment by hibri** [comment]
Hi @seanamosw , it was intentional, when I first wrote the library, NUnit was what we used, it has worked in for most scenarios. 
It's not idea however. I intend to remove the dependencies, and take a similar approach to Coypu.
https://github.com/featurist/coypu/tree/master/src/Coypu.NUnit

It needs some work. Happy to take a PR if you are up for the challenge. I'm busy with other projects at the moment. :)

**Comment by jesaremi** [comment]
Please consider removing NUnit dependency. We don't use it at all. A mocking framework should work independent of the Unit testing framework.

**Comment by hibri** [comment]
Hi @jesaremi It is in the plan, and to move the assertions to a separate library. NUnit is used to provide the assertions only. I don't want to pull it out right away, without giving an alternative because the features are in use.

**Comment by jesaremi** [comment]
Thank you! Otherwise it's a really useful and intuitive framework. Thanks for creating it

**Comment by hibri** [comment]
Hi @jesaremi @seanamosw, 
I've published a new alpha package, removing the NUnit depedency. would love some feedback if this works on your projects before I publish a new 2.0 version.

Thanks

**Comment by hibri** [comment]
Fixed in #67
